services:
  app:
    container_name: "glpi-test-app"
    image: "ghcr.io/glpi-project/${PHP_IMAGE:-githubactions-php-apache:8.3}"
    environment:
      CODE_COVERAGE: "${CODE_COVERAGE:-false}"
    command:
      - apt install --assume-yes --no-install-recommends --quiet wget
      - wget -q https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
      - apt install --assume-yes --no-install-recommends --quiet ./google-chrome-stable_current_amd64.deb
    volumes:
      - type: "bind"
        source: "${APPLICATION_ROOT}"
        target: "/var/www/glpi"
      - type: "bind"
        source: "${APP_CONTAINER_HOME}"
        target: "/home/www-data"
