name: "Trigger Docker releases"

on:
  release:
    types: [released]

jobs:
  trigger-docker-releases:
    name: "Trigger Docker releases"
    uses: "glpi-project/docker-images/.github/workflows/glpi.yml@main"
    secrets: inherit
    with:
        glpi-version: "${{ github.event.release.tag_name }}"
